### 1. Transfer Learning for Image Classification1

#### It is highly recommended that you complete this project using Keras2 and Python. 

#### a) In this problem, we are trying to build a classifier that distinguishes images of 20 bird species. You are provided with text data in twenty folders.

#### b) Data Exploration and Pre-processing
#####  i. Images in each class are given in separate folders. The file Classes.xlsx pro- vides the classes assigned to the bird species images in each folder. Therefore, you encode your classes using one-hot encoding and Classes.xlsx.

In [66]:
import pandas as pd
import numpy as np
import os
import random
import cv2

In [12]:
df = pd.read_excel('Data/Classes.xlsx')
df.columns=['folder_name','class']
lis_birds=df['folder_name'].tolist()
print(lis_birds)

['005.Crested_Auklet', '013.Bobolink', '015.Lazuli_Bunting', '023.Brandt_Cormorant', '040.Olive_sided_Flycatcher', '041.Scissor_tailed_Flycatcher', '067.Anna_Hummingbird', '072.Pomarine_Jaeger', '076.Dark_eyed_Junco', '081.Pied_Kingfisher', '082.Ringed_Kingfisher', '086.Pacific_Loon', '099.Ovenbird', '104.American_Pipit', '127.Savannah_Sparrow', '135.Bank_Swallow', '141.Artic_Tern', '149.Brown_Thrasher', '156.White_eyed_Vireo', '168.Kentucky_Warbler']

In [6]:
df.head()

                  folder_name  class
0          005.Crested_Auklet      0
1                013.Bobolink      1
2          015.Lazuli_Bunting      2
3        023.Brandt_Cormorant      3
4  040.Olive_sided_Flycatcher      4

In [7]:
classes = df['class'].unique()

In [8]:
class_dict = {}
for c in classes:
    one_hot = np.array(np.eye(len(classes))[c])
    class_dict[c] = one_hot

In [9]:
for _, row in df.iterrows():
    image_id = row['folder_name']
    image_class = row['class']
    one_hot = class_dict[image_class]
    # Use the one-hot encoded vector for further processing or analysis

In [18]:
one_hot_df = pd.get_dummies(df['class'])

one_hot_df = pd.DataFrame(lis_birds, columns=['bird']).join(one_hot_df)




one_hot_df

cols = one_hot_df.columns.to_list()[1:]

# Rename the selected columns
one_hot_df = one_hot_df.rename(columns=dict(zip(cols, lis_birds)))
one_hot_df

,bird,005.Crested_Auklet,013.Bobolink,015.Lazuli_Bunting,023.Brandt_Cormorant,040.Olive_sided_Flycatcher,041.Scissor_tailed_Flycatcher,067.Anna_Hummingbird,072.Pomarine_Jaeger,076.Dark_eyed_Junco,...,082.Ringed_Kingfisher,086.Pacific_Loon,099.Ovenbird,104.American_Pipit,127.Savannah_Sparrow,135.Bank_Swallow,141.Artic_Tern,149.Brown_Thrasher,156.White_eyed_Vireo,168.Kentucky_Warbler
0,005.Crested_Auklet,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,013.Bobolink,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,015.Lazuli_Bunting,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,023.Brandt_Cormorant,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,040.Olive_sided_Flycatcher,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,041.Scissor_tailed_Flycatcher,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,067.Anna_Hummingbird,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7,072.Pomarine_Jaeger,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8,076.Dark_eyed_Junco,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,081.Pied_Kingfisher,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,082.Ringed_Kingfisher,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,086.Pacific_Loon,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,099.Ovenbird,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,104.American_Pipit,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,127.Savannah_Sparrow,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,135.Bank_Swallow,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
16,141.Artic_Tern,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
17,149.Brown_Thrasher,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
18,156.White_eyed_Vireo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19,168.Kentucky_Warbler,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

#### ii. Randomly select ⌈0.7ni⌉ images from each folder as your training set, ⌈0.15ni⌉ as validation set, and the rest as your test set, where ni is the number of images in folder i and ⌈x⌉ is the ceiling of x.

In [35]:
# List the files in the 'my_folder' directory
file_names = os.listdir('Data/images/')

# Filter out directories from the list of file names
#file_names = [file for file in file_names if os.path.isfile(os.path.join('my_folder', file))]

# Print the names of the files in the directory
#print(file_names)
file_names=list(file_names)
file_names_1=[]

for i in range(0,len(file_names)):
    file_names_1.append('Data/images/'+ str(file_names[i]))
file_names_1=file_names_1[:-1]
file_names_1

['Data/images/005.Crested_Auklet',
 'Data/images/015.Lazuli_Bunting',
 'Data/images/156.White_eyed_Vireo',
 'Data/images/081.Pied_Kingfisher',
 'Data/images/135.Bank_Swallow',
 'Data/images/086.Pacific_Loon',
 'Data/images/067.Anna_Hummingbird',
 'Data/images/076.Dark_eyed_Junco',
 'Data/images/149.Brown_Thrasher',
 'Data/images/127.Savannah_Sparrow',
 'Data/images/041.Scissor_tailed_Flycatcher',
 'Data/images/141.Artic_Tern',
 'Data/images/082.Ringed_Kingfisher',
 'Data/images/099.Ovenbird',
 'Data/images/013.Bobolink',
 'Data/images/104.American_Pipit',
 'Data/images/023.Brandt_Cormorant',
 'Data/images/168.Kentucky_Warbler',
 'Data/images/072.Pomarine_Jaeger',
 'Data/images/040.Olive_sided_Flycatcher']

In [65]:
def get_three_list(my_list):
    # Import the random module

    # Define the list of elements
    #my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,16,17,18,19,20]

    # Select 70% of the elements using the sample() method
    selected_70 = random.sample(my_list, int(len(my_list) * 0.7))

    my_list = [x for x in my_list if x not in selected_70]

    # Select 15% of the elements using the sample() method
    selected_15 = random.sample(my_list, int(len(my_list) * 0.5))

    # Remove the selected elements from the original list
    my_list = [x for x in my_list if x not in selected_15]
    #print(my_list)

    # Select 5% of the elements using the sample() method
    selected_5 = my_list

    # Print the selected elements
    #     print(selected_70)
    #     print(selected_15)
    #     print(selected_5)
    
    return selected_70,selected_15,selected_5



training_set=[]
validation_set=[]
test_set=[]

for folder in file_names_1:
    temp_train=[]
    temp_val=[]
    temp_test=[]
    
    file_names = os.listdir(folder)
    
    for i in range(0,len(file_names)):
        file_names[i]=folder+'/'+file_names[i]
    
    temp_train,temp_val,temp_test=get_three_list(file_names)
    
    
    training_set.extend(temp_train)
    validation_set.extend(temp_val)
    test_set.extend(temp_test)

#print(validation_set)

#### iii. In order for all the images to have the same size, zero-pad or resize the images in your dataset. This can be done using various tools, including OpenCV.

In [74]:
# Import the cv2 module




# Define the desired size of the image
desired_size = (256, 256)

for i in range(0,len(training_set)):
    
    image_name=training_set[i].split('/')[-1]
    
    
    image = cv2.imread(training_set[i])

    # Use the resize() method to resize the image
    image = cv2.resize(image, desired_size)
    
    

    folder = 'Train'

    # Use the os module to construct the file path
    file_path = os.path.join(folder, image_name)

    # Save the resized image to the file using the imwrite() method
    cv2.imwrite(file_path, image)
    
    

    
for i in range(0,len(validation_set)):
    
    image_name=validation_set[i].split('/')[-1]
    
    
    image = cv2.imread(validation_set[i])

    # Use the resize() method to resize the image
    image = cv2.resize(image, desired_size)
    
    

    folder = 'Validation'

    # Use the os module to construct the file path
    file_path = os.path.join(folder, image_name)

    # Save the resized image to the file using the imwrite() method
    cv2.imwrite(file_path, image)


    
for i in range(0,len(test_set)):
    
    image_name=test_set[i].split('/')[-1]
    
    
    image = cv2.imread(test_set[i])

    # Use the resize() method to resize the image
    image = cv2.resize(image, desired_size)
    
    

    folder = 'test'

    # Use the os module to construct the file path
    file_path = os.path.join(folder, image_name)

    # Save the resized image to the file using the imwrite() method
    cv2.imwrite(file_path, image)

In [69]:
lis=[1,2,3]
print(lis[-1])

3